version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: np
    versions:
    - 7.2.0
    - 7.3.0
    - 7.4.0
