name: Continuous Integration
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm run test

    strategy:
      matrix:
        node-version: [20]
        os: [ubuntu-latest]
