name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Test
        run: npm run test
    strategy:
      matrix:
        node-version: [18]
        os: [ubuntu-latest]
